apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksapi-deployment
  labels:
    app: booksapi
spec:
  selector:
    matchLabels:
      app: booksapi
  template:
    metadata:
      labels:
        app: booksapi
    spec:
      containers:
      - name: booksapi
        image: booksapi:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ConnectionStrings__SqlServer
          value: Server=mssql-booksdb-clusterip,1433;User Id=SA;Password=Pa55w0rd2022
        - name: ConnectionStrings__SqlDatabase
          value: Server=mssql-booksdb-clusterip,1433;Database=BooksDb;User Id=SA;Password=Pa55w0rd2022;
---
apiVersion: v1
kind: Service
metadata:
  name: booksapi
spec:
  type: LoadBalancer
  selector:
    app: booksapi
  ports:
  - port: 8083
    targetPort: 80
    protocol: TCP

