apiVersion: apps/v1
kind: Deployment
metadata:
  name: webstatus-deployment
spec:
  selector:
    matchLabels:
      app: webstatus
  template:
    metadata:
      labels:
        app: webstatus
    spec:
      containers:
      - name: webstatus
        image: webstatus
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development

        - name: HealthChecks-UI__HealthChecks__0__Name
          value: Courses.API Health Check
        - name: HealthChecks-UI__HealthChecks__0__Uri
          value: http://coursesapi-clusterip/hc

        - name: HealthChecks-UI__HealthChecks__1__Name
          value: GeneralStore.API Health Check
        - name: HealthChecks-UI__HealthChecks__1__Uri
          value: http://generalstoreapi-clusterip-service/hc

        - name: HealthChecks-UI__HealthChecks__2__Name
          value: Books.API Health Check
        - name: HealthChecks-UI__HealthChecks__2__Uri
          value: http://booksapi-clusterip/hc

        - name: HealthChecks-UI__HealthChecks__3__Name
          value: AzureStore.API Health Check
        - name: HealthChecks-UI__HealthChecks__3__Uri
          value: http://azurestoreapi-clusterip/hc

        - name: HealthChecks-UI__HealthChecks__4__Name
          value: Movies.API Health Check
        - name: HealthChecks-UI__HealthChecks__4__Uri
          value: http://moviesapi-clusterip/hc

        - name: HealthChecks-UI__HealthChecks__5__Name
          value: Series.API Health Check
        - name: HealthChecks-UI__HealthChecks__5__Uri
          value: http://seriesapi-clusterip/hc
---
apiVersion: v1
kind: Service
metadata:
  name: webstatus-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: webstatus
  ports:
  - port: 8090
    targetPort: 80
    protocol: TCP

          
