version: '3.9'

services:
  coursesdb:
    container_name: coursesdb
    restart: always
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Pa55w0rd2022"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"

  storedb:
    container_name: storedb
    restart: always
    ports:
      - 1434:1433 #1343 pour y acceder mais 1433 car c est le port de SQL server. On ne le change pas
    environment:
      SA_PASSWORD: "Pa55w0rd2022"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672 #rabbitmq
      - 15672:15672 #rabbitmq management dashboard

  #pw admin1234
  portainer:
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9000:9000 #9000 plutot que 9443 parce que http et non https

  courses.api:
    container_name: courses-api
    depends_on:
      - coursesdb
      - rabbitmq
    ports:
      - 8000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SqlDatabase=Server=coursesdb,1433;Database=CoursesDb;User Id=SA;Password=Pa55w0rd2022;"
      - "RabbitMQHost=rabbitmq"
      - "RabbitMQPort=5672"
      - "GrpcCourseServer=http://generalstore-api:666" #666 port du http2 de grpc

  generalstore.api:
    container_name: generalstore-api
    depends_on:
      - storedb
      - rabbitmq
    ports:
      - 8001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SqlDatabase=Server=storedb,1433;Database=StoreDb;User Id=SA;Password=Pa55w0rd2022;"
      - "RabbitMQHost=rabbitmq"
      - "RabbitMQPort=5672"
      - "Kestrel:Endpoints:WebApi:Url=http://generalstore-api:80" #Http1
      - "Kestrel:Endpoints:Grpc:Url=http://generalstore-api:666" #Http2