version: '3.9'

services:
  coursesdb:
    container_name: coursesdb
    restart: always
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Pa55w0rd2022"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"

  storedb:
    container_name: storedb
    restart: always
    ports:
      - 1434:1433 #1343 pour y acceder mais 1433 car c est le port de SQL server. On ne le change pas
    environment:
      SA_PASSWORD: "Pa55w0rd2022"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"

  booksdb:
    container_name: booksdb
    restart: always
    ports:
      - 1435:1433 #1343 pour y acceder mais 1433 car c est le port de SQL server. On ne le change pas
    environment:
      SA_PASSWORD: "Pa55w0rd2022"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"

  moviesdb:
    container_name: moviesdb
    restart: always
    ports:
      - 1436:1433 #1343 pour y acceder mais 1433 car c est le port de SQL server. On ne le change pas
    environment:
      SA_PASSWORD: "Pa55w0rd2022"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"

  redisdb:
    container_name: redisdb
    restart: always
    ports:
      - 6379:6379

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672 #rabbitmq
      - 15672:15672 #rabbitmq management dashboard

  #pw admin1234
  portainer:
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9000:9000 #9000 plutot que 9443 parce que http et non https

  courses.api:
    container_name: courses-api
    depends_on:
      - coursesdb
      - rabbitmq
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SqlDatabase=Server=coursesdb,1433;Database=CoursesDb;User Id=SA;Password=Pa55w0rd2022;"
      - "RabbitMQHost=rabbitmq"
      - "RabbitMQPort=5672"
      - "GrpcCourseServer=http://generalstore-api:666" #666 port du http2 de grpc

  generalstore.api:
    container_name: generalstore-api
    depends_on:
      - storedb
      - rabbitmq
    ports:
      - 5001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SqlDatabase=Server=storedb,1433;Database=StoreDb;User Id=SA;Password=Pa55w0rd2022;"
      - "RabbitMQHost=rabbitmq"
      - "RabbitMQPort=5672"
      - "Kestrel:Endpoints:WebApi:Url=http://generalstore-api:80" #Http1
      - "Kestrel:Endpoints:Grpc:Url=http://generalstore-api:666" #Http2

  books.api:
    container_name: books-api
    depends_on:
      - booksdb
    ports:
      - 5002:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SqlServer=Server=booksdb,1433;User Id=SA;Password=Pa55w0rd2022;" 
      - "ConnectionStrings:SqlDatabase=Server=booksdb,1433;Database=BooksDb;User Id=SA;Password=Pa55w0rd2022;"

  azurestore.api:
    container_name: azurestore-api
    ports:
      - 5003:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:ServiceBusUrl=Endpoint=sb://microservices-devops.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=pDR+Gy2ZFAnUVKQST5fx2ZjOq73fGKoNmuNPBBnnLI8="
      - "ConnectionStrings:QueueName=zafina-queue"
      - "ApplicationInsights:InstrumentationKey=InstrumentationKey=0ed1861e-a393-4834-a005-3919002bb4fb;IngestionEndpoint=https://francecentral-1.in.applicationinsights.azure.com/"

  movies.api:
    container_name: movies-api
    ports:
      - 5004:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SqlServer=Server=moviesdb,1433;User Id=SA;Password=Pa55w0rd2022;" 
      - "ConnectionStrings:SqlDatabase=Server=moviesdb,1433;Database=MoviesDb;User Id=SA;Password=Pa55w0rd2022;"

  series.api:
    container_name: series-api
    ports:
      - 5005:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Redis=redisdb:6379"
    depends_on:
      - redisdb
      