version: '3.9'

services:
  coursesdb:
    container_name: coursesdb
    restart: always
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Pa55w0rd2022"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"

  courses.api:
    container_name: courses-api
    depends_on:
      - coursesdb
    ports:
      - 8000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SqlDatabase=Server=coursesdb,1433;Database=myDataBase;User Id=SA;Password=Pa55w0rd2022;"
