version: '3.9'

services:
  coursesdb:
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
  
  courses.api:
    image: coursesapi
    build: .
      #context: .
      #dockerfile: src/services/Courses.API/Dockerfile
      
